### ISSUE TITLE
not start

### ISSUE THREAD

**Issue by GregTCLTK** [CCO-de/Flashbot#1]
Bei mir startet der Bot nicht wenn ich die readme.md datei ausführe
ich gebe halt py readme.md ein aber es geht net ;(

**Comment by LeeDJD** [comment]
was n kak bot

**Comment by GregTCLTK** [comment]
Ja voll komisch musste nicht mal einen Token eingeben

**Comment by DRSchlaubi** [comment]
Ja versteh ich auch nicht
